### ISSUE TITLE
Changes made in PD11 GUI are not reflected in docker-machine

### ISSUE THREAD

**Issue by y3ddet** [Parallels/docker-machine#1]
Any change to the VM configuration made in the GUI does not appear through the CLI, for example changing the amount of RAM or CPUs. It looks like the .docker/machine/machines/name/config.json is used to answer "docker-machine inspect name" and not calls to prlctl

**Comment by legal90** [comment]
@y3ddet Please, describe by steps what exactly are you trying to do.

> It looks like the .docker/machine/machines/name/config.json is used to answer "docker-machine inspect name" and not calls to prlctl

Yes, it is. That's the common behavior for Machine and that's why the recommended way for VM configuration is specifying options on the `create` step, like this:
```console
$ docker-machine create --driver=parallels --parallels-cpu-count 2 --parallels-memory 2048 prl-dev
```
Details: https://github.com/Parallels/docker-machine#usage

**Comment by y3ddet** [comment]
@legal90 then this is a "feature" of the upstream docker-machine, i.e.: machine assumes that changes are only made through the machine CLI.  I was able to use the cpu and mem options to get a more or less correct VM.

You close it as an issue, but at least it's here for documentation.

**Comment by legal90** [comment]
If you configure the stopped VM through GUI or `prlctl` utility, these changes actually will be applied, but config.json won't not be updated.
