### ISSUE TITLE
Docker machine creation issue. 

### ISSUE THREAD

**Issue by a-am** [Parallels/docker-machine#4]
When running ```docker-machine create -d parallels prl-dev```  I end up receiving an error: 
```
Creating SSH key...
Creating Parallels Desktop VM...
Starting Parallels Desktop VM...
Waiting for VM to come online...
Error creating machine: Error mounting shared folder: exit status 255
You will want to check the provider to make sure the machine and associated resources were properly removed.```

- Parallels Desktop Pro: Version 11.0.0 (31193)
- Docker: Version 1.8.1

**Comment by a-am** [comment]
I also get this error when running ```docker-machine env prl-dev```:
```.docker/machine/machines/prl-dev/ca.pem: no such file or directory```

**Comment by legal90** [comment]
> Error creating machine: Error mounting shared folder: exit status 255

@a-am Is this error appears constantly, for all new machines? If so, please show the verbose output of this error:
```console
docker-machine create -d parallels prl-dev-2 --debug
```
The failed machine could be deleted with:
```
docker-machine rm -f <vm_name>
```

P.s.
> .docker/machine/machines/prl-dev/ca.pem: no such file or directory

This error is caused by the first one. Certificates were not synced because the process has stopped earlier.

**Comment by a-am** [comment]
It is no longer throwing those errors. After I ran the suggested command now creating a machine seems to work flawlessly.  Puzzling.

**Comment by nissan** [comment]
I still experience the error even after running the `docker-machine rm -f pro-dev` suggested above.
Below is my output from executing:  `docker-machine create -d parallels prl-dev --debug`
`
executing: prlctl --version
executing: prlsrvctl info --license
Creating SSH key...
Creating Parallels Desktop VM...
executing: prlctl create prl-dev --distribution boot2docker --dst /Users/nissandookeran/.docker/machine/machines/prl-dev --no-hdd
Creating the virtual machine...
Generate the VM configuration for boot2docker.
Remove the hdd0 device.
The VM has been successfully created.
executing: prlctl set prl-dev --select-boot-device off --cpus 1 --memsize 1024 --cpu-hotplug off --nested-virt on --pmu-virt on --on-window-close keep-running --longer-battery-life on --3d-accelerate off --device-bootorder cdrom0
set cpus(8): 1
set cpu hotplug: 0
Set the memsize parameter to 1024Mb.
Set 3d acceleration: 0.

The VM has been successfully configured.
executing: prlctl set prl-dev --device-set cdrom0 --iface sata --position 0 --image /Users/nissandookeran/.docker/machine/machines/prl-dev/boot2docker.iso
Creating cdrom0 (+) sata:0 image='/Users/nissandookeran/.docker/machine/machines/prl-dev/boot2docker.iso'

Configured cdrom0 (+) sata:0 image='/Users/nissandookeran/.docker/machine/machines/prl-dev/boot2docker.iso'


The VM has been successfully configured.
executing: prlctl set prl-dev --device-add hdd --iface sata --position 1 --image /Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd --type plain --size 32
The folder /Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd does not exist. Specify another folder and try again.
Creating hdd0 (+) sata:1 image='/Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd' type='plain' 32Mb

Created hdd0 (+) sata:1 image='/Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd' type='plain' 32Mb


The VM has been successfully configured.
HDS image path: /Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd/disk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
executing: prl_disk_tool convert --expanding --hdd /Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd
Operation progress 100 %
executing: prl_disk_tool resize --hdd /Users/nissandookeran/.docker/machine/machines/prl-dev/disk.hdd --size 20000
Operation progress 100 %
executing: prlctl set prl-dev --time-sync off

The VM has been successfully configured.
executing: prlctl set prl-dev --startup-view headless

The VM has been successfully configured.
executing: prlctl set prl-dev --shf-host on

The VM has been successfully configured.
executing: prlctl set prl-dev --shf-host-add Users --path /Users
Creating shared folder: Users (+) path='/Users' mode='rw'


The VM has been successfully configured.
Starting Parallels Desktop VM...
executing: prlctl start prl-dev
Starting the VM...
The VM has been successfully started.
Waiting for VM to come online...
executing: prlctl list -i prl-dev
Not there yet 1/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 2/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 3/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 4/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 5/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 6/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 7/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 8/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 9/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 10/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Not there yet 11/60, error: IP lease not found for MAC address 001C4202166E in: /Library/Preferences/Parallels/parallels_dhcp_leases

executing: prlctl list -i prl-dev
Found lease: 10.211.55.18 for MAC: 001C4202166E, expiring at 1444801252, leased for 1800 s.

Found IP lease: 10.211.55.18 for MAC address 001C4202166E

Got an ip: 10.211.55.18
executing: prlctl list prl-dev --output status --no-header
Getting to WaitForSSH function...
executing: prlctl list prl-dev --output status --no-header
executing: prlctl list -i prl-dev
Found lease: 10.211.55.18 for MAC: 001C4202166E, expiring at 1444801252, leased for 1800 s.

Found IP lease: 10.211.55.18 for MAC address 001C4202166E

Testing TCP connection to: 10.211.55.18:22
executing: prlctl list prl-dev --output status --no-header
executing: prlctl list -i prl-dev
Found lease: 10.211.55.18 for MAC: 001C4202166E, expiring at 1444801252, leased for 1800 s.

Found IP lease: 10.211.55.18 for MAC address 001C4202166E

Using SSH client type: external
About to run SSH command:
exit 0
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/nissandookeran/.docker/machine/machines/prl-dev/id_rsa -p 22 docker@10.211.55.18 exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 
executing: prlctl list prl-dev --output status --no-header
executing: prlctl list -i prl-dev
Found lease: 10.211.55.18 for MAC: 001C4202166E, expiring at 1444801252, leased for 1800 s.

Found IP lease: 10.211.55.18 for MAC address 001C4202166E

executing: prlctl list prl-dev --output status --no-header
executing: prlctl list -i prl-dev
Found lease: 10.211.55.18 for MAC: 001C4202166E, expiring at 1444801252, leased for 1800 s.

Found IP lease: 10.211.55.18 for MAC address 001C4202166E

Using SSH client type: external
About to run SSH command:
sudo mkdir -p /Users && sudo mount -t prl_fs Users /Users
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/nissandookeran/.docker/machine/machines/prl-dev/id_rsa -p 22 docker@10.211.55.18 sudo mkdir -p /Users && sudo mount -t prl_fs Users /Users] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: exit status 255: mount: mounting Users on /Users failed: No such device

Error creating machine: Error mounting shared folder: exit status 255
You will want to check the provider to make sure the machine and associated resources were properly removed.
`

**Comment by legal90** [comment]
@nissan At this moment it is related to another issue: https://github.com/Parallels/docker-machine/issues/7#issuecomment-147695317
The compatibility with Parallels Desktop is broken in Boot2Docker v1.8.3
