### ISSUE TITLE
Can't pull any image

### ISSUE THREAD

**Issue by krasilich** [Parallels/docker-machine#9]
~~~
$ docker-machine -v
docker-machine version 0.4.0-1 (1981be6)
~~~

Create machine

~~~
$ docker-machine create --driver=parallels dev-prl
~~~

Export docker client config values and try to run container, for example

~~~
docker run busybox echo hello world
~~~

And get this

~~~
Unable to find image 'busybox:latest' locally
Pulling repository docker.io/library/busybox
Get https://registry-1.docker.io/v1/repositories/library/busybox/tags/latest: dial tcp: lookup registry-1.docker.io: no such host
~~~

Any ideas what's the issue and how to fix?

UPD: It works with VirtualBox driver. And I've tried to use older boot2docker releases with --parallels-boot2docker-url option - the same result

Thanks

**Comment by legal90** [comment]
Seems like there is some networking problem. Please, ensure that the mentioned host is available from your Mac host:
```bash
$ curl https://registry-1.docker.io/v1/repositories/library/busybox/tags/latest
{"error": "Requires authorization"}  # That's OK
```

Then check the DNS configuration in the VM:
```console
$ docker-machine ssh dev-prl -- cat /etc/resolv.conf
search localdomain
nameserver 10.211.55.1
```

```console
$ docker-machine ssh dev-prl -- nslookup registry-1.docker.io
Server:    10.211.55.1
Address 1: 10.211.55.1

Name:      registry-1.docker.io
Address 1: 54.152.85.16 ec2-54-152-85-16.compute-1.amazonaws.com
Address 2: 52.4.102.223 ec2-52-4-102-223.compute-1.amazonaws.com
Address 3: 54.175.248.102 ec2-54-175-248-102.compute-1.amazonaws.com
Address 4: 52.22.213.10 ec2-52-22-213-10.compute-1.amazonaws.com
Address 5: 54.85.1.130 ec2-54-85-1-130.compute-1.amazonaws.com
Address 6: 52.3.205.191 ec2-52-3-205-191.compute-1.amazonaws.com
```

**Comment by krasilich** [comment]
@legal90 thanks for quick reply.

The only little difference is in last command
~~
$ docker-machine ssh dev-prl -- nslookup registry-1.docker.io
Server:    10.211.55.1
Address 1: 10.211.55.1

Name:      registry-1.docker.io
Address 1: 54.175.248.102 ec2-54-175-248-102.compute-1.amazonaws.com
Address 2: 52.4.102.223 ec2-52-4-102-223.compute-1.amazonaws.com
Address 3: 54.85.1.130 ec2-54-85-1-130.compute-1.amazonaws.com
~~

But ips still the same, so I think it's not critical.

**Comment by legal90** [comment]
Hm.. Since the domain name is resolved, your `docker run` should work fine. Have you tried to run it again?
What happens if you run the same run command from the VM (after logging in via `docker-machine ssh dev-prl`).

It looks like the problem is not related to Docker Machine driver.

**Comment by krasilich** [comment]
I've tried to run it inside boot2docker but got same result.
I agree that the issue might not be related to docker machine driver.
I'll investigate it a little bit more, anyway
Will keep updated.

**Comment by krasilich** [comment]
Seems like it was temp issue with internet connection or something like that, it works now.
Thanks

**Comment by legal90** [comment]
Seems like this issue have been reproduced again: https://github.com/Parallels/docker-machine-parallels/issues/11
